-- 1. Εισαγωγή Χωρών/Περιοχών (5 εγγραφές)
INSERT INTO COUNTRY (COUNTRY_ID, NAME) VALUES (1, 'Ελλάδα');
INSERT INTO COUNTRY (COUNTRY_ID, NAME) VALUES (2, 'Ιταλία');
INSERT INTO COUNTRY (COUNTRY_ID, NAME) VALUES (3, 'Γαλλία');
INSERT INTO COUNTRY (COUNTRY_ID, NAME) VALUES (4, 'Μεξικό');
INSERT INTO COUNTRY (COUNTRY_ID, NAME) VALUES (5, 'Κίνα');

-- 2. Εισαγωγή Κατηγοριών (5 εγγραφές)
INSERT INTO CATEGORY (CATEGORY_ID, CNAME) VALUES (1, 'Θαλασσινά');
INSERT INTO CATEGORY (CATEGORY_ID, CNAME) VALUES (2, 'Ζυμαρικά');
INSERT INTO CATEGORY (CATEGORY_ID, CNAME) VALUES (3, 'Γλυκά');
INSERT INTO CATEGORY (CATEGORY_ID, CNAME) VALUES (4, 'Κρεατικά');
INSERT INTO CATEGORY (CATEGORY_ID, CNAME) VALUES (5, 'Vegan');

-- 3. Εισαγωγή Υλικών (40 εγγραφές)
INSERT INTO INGREDIENT (INGREDIENT_ID, INAME, DESCRIPTION) VALUES (1, 'Ελαιόλαδο', 'Εξαιρετικό παρθένο ελαιόλαδο');
INSERT INTO INGREDIENT (INGREDIENT_ID, INAME, DESCRIPTION) VALUES (2, 'Αλεύρι', 'Αλεύρι για όλες τις χρήσεις');
INSERT INTO INGREDIENT (INGREDIENT_ID, INAME, DESCRIPTION) VALUES (3, 'Ντομάτα', 'Φρέσκια ντομάτα');
INSERT INTO INGREDIENT (INGREDIENT_ID, INAME, DESCRIPTION) VALUES (4, 'Κρεμμύδι', 'Ξερό κρεμμύδι');
INSERT INTO INGREDIENT (INGREDIENT_ID, INAME, DESCRIPTION) VALUES (5, 'Σκόρδο', 'Φρέσκο σκόρδο');
INSERT INTO INGREDIENT (INGREDIENT_ID, INAME, DESCRIPTION) VALUES (6, 'Αλάτι', 'Θαλασσινό αλάτι');
INSERT INTO INGREDIENT (INGREDIENT_ID, INAME, DESCRIPTION) VALUES (7, 'Πιπέρι', 'Μαύρο πιπέρι');
INSERT INTO INGREDIENT (INGREDIENT_ID, INAME, DESCRIPTION) VALUES (8, 'Βασιλικός', 'Φρέσκα φύλλα βασιλικού');
INSERT INTO INGREDIENT (INGREDIENT_ID, INAME, DESCRIPTION) VALUES (9, 'Ρίγανη', 'Αποξηραμένη ρίγανη');
INSERT INTO INGREDIENT (INGREDIENT_ID, INAME, DESCRIPTION) VALUES (10, 'Μακαρόνια', 'Σπαγγέτι No 7');
INSERT INTO INGREDIENT (INGREDIENT_ID, INAME, DESCRIPTION) VALUES (11, 'Μοσχάρι', 'Φιλέτο μοσχαρίσιο');
INSERT INTO INGREDIENT (INGREDIENT_ID, INAME, DESCRIPTION) VALUES (12, 'Κοτόπουλο', 'Στήθος κοτόπουλο');
INSERT INTO INGREDIENT (INGREDIENT_ID, INAME, DESCRIPTION) VALUES (13, 'Φέτα', 'Ελληνική φέτα ΠΟΠ');
INSERT INTO INGREDIENT (INGREDIENT_ID, INAME, DESCRIPTION) VALUES (14, 'Παρμεζάνα', 'Parmigiano Reggiano');
INSERT INTO INGREDIENT (INGREDIENT_ID, INAME, DESCRIPTION) VALUES (15, 'Ρύζι', 'Ρύζι μπασμάτι');
INSERT INTO INGREDIENT (INGREDIENT_ID, INAME, DESCRIPTION) VALUES (16, 'Ζάχαρη', 'Λευκή κρυσταλλική ζάχαρη');
INSERT INTO INGREDIENT (INGREDIENT_ID, INAME, DESCRIPTION) VALUES (17, 'Αυγά', 'Φρέσκα αυγά ελευθέρας βοσκής');
INSERT INTO INGREDIENT (INGREDIENT_ID, INAME, DESCRIPTION) VALUES (18, 'Γάλα', 'Πλήρες φρέσκο γάλα');
INSERT INTO INGREDIENT (INGREDIENT_ID, INAME, DESCRIPTION) VALUES (19, 'Βούτυρο', 'Αγελαδινό βούτυρο');
INSERT INTO INGREDIENT (INGREDIENT_ID, INAME, DESCRIPTION) VALUES (20, 'Σοκολάτα', 'Σοκολάτα υγείας 70%');
INSERT INTO INGREDIENT (INGREDIENT_ID, INAME, DESCRIPTION) VALUES (21, 'Λεμόνι', 'Φρέσκα λεμόνια');
INSERT INTO INGREDIENT (INGREDIENT_ID, INAME, DESCRIPTION) VALUES (22, 'Κρασί', 'Λευκό ξηρό κρασί');
INSERT INTO INGREDIENT (INGREDIENT_ID, INAME, DESCRIPTION) VALUES (23, 'Μαϊντανός', 'Φρέσκος μαϊντανός');
INSERT INTO INGREDIENT (INGREDIENT_ID, INAME, DESCRIPTION) VALUES (24, 'Μουστάρδα', 'Μουστάρδα απαλή');
INSERT INTO INGREDIENT (INGREDIENT_ID, INAME, DESCRIPTION) VALUES (25, 'Μέλι', 'Θυμαρίσιο μέλι');
INSERT INTO INGREDIENT (INGREDIENT_ID, INAME, DESCRIPTION) VALUES (26, 'Σουσάμι', 'Λευκό σουσάμι');
INSERT INTO INGREDIENT (INGREDIENT_ID, INAME, DESCRIPTION) VALUES (27, 'Γαρίδες', 'Φρέσκες γαρίδες');
INSERT INTO INGREDIENT (INGREDIENT_ID, INAME, DESCRIPTION) VALUES (28, 'Καλαμάρι', 'Φρέσκο καλαμάρι');
INSERT INTO INGREDIENT (INGREDIENT_ID, INAME, DESCRIPTION) VALUES (29, 'Σάλτσα Σόγιας', 'Light soy sauce');
INSERT INTO INGREDIENT (INGREDIENT_ID, INAME, DESCRIPTION) VALUES (30, 'Τζίντζερ', 'Φρέσκια ρίζα τζίντζερ');
INSERT INTO INGREDIENT (INGREDIENT_ID, INAME, DESCRIPTION) VALUES (31, 'Tortilla', 'Πίτες για τάκος');
INSERT INTO INGREDIENT (INGREDIENT_ID, INAME, DESCRIPTION) VALUES (32, 'Avocado', 'Ώριμο αβοκάντο');
INSERT INTO INGREDIENT (INGREDIENT_ID, INAME, DESCRIPTION) VALUES (33, 'Chili', 'Κόκκινες πιπεριές τσίλι');
INSERT INTO INGREDIENT (INGREDIENT_ID, INAME, DESCRIPTION) VALUES (34, 'Κανέλα', 'Κανέλα Κεϋλάνης');
INSERT INTO INGREDIENT (INGREDIENT_ID, INAME, DESCRIPTION) VALUES (35, 'Βανίλια', 'Εκχύλισμα βανίλιας');
INSERT INTO INGREDIENT (INGREDIENT_ID, INAME, DESCRIPTION) VALUES (36, 'Μελιτζάνα', 'Φλάσκες μελιτζάνες');
INSERT INTO INGREDIENT (INGREDIENT_ID, INAME, DESCRIPTION) VALUES (37, 'Πατάτες', 'Πατάτες Νάξου');
INSERT INTO INGREDIENT (INGREDIENT_ID, INAME, DESCRIPTION) VALUES (38, 'Κιμάς', 'Μοσχαρίσιος κιμάς λάπα');
INSERT INTO INGREDIENT (INGREDIENT_ID, INAME, DESCRIPTION) VALUES (39, 'Μπεσαμέλ', 'Έτοιμο μείγμα μπεσαμέλ');
INSERT INTO INGREDIENT (INGREDIENT_ID, INAME, DESCRIPTION) VALUES (40, 'Μανιτάρια', 'Μανιτάρια πλευρώτους');

-- 4. Εισαγωγή Χρηστών (5 εγγραφές)
INSERT INTO APP_USER (EMAIL, NAME, LNAME) VALUES ('nikos@mail.com', 'Νίκος', 'Παπαδόπουλος');
INSERT INTO APP_USER (EMAIL, NAME, LNAME) VALUES ('maria@mail.com', 'Μαρία', 'Γεωργίου');
INSERT INTO APP_USER (EMAIL, NAME, LNAME) VALUES ('eleni@mail.com', 'Ελένη', 'Δημητρίου');
INSERT INTO APP_USER (EMAIL, NAME, LNAME) VALUES ('kostas@mail.com', 'Κώστας', 'Νικολάου');
INSERT INTO APP_USER (EMAIL, NAME, LNAME) VALUES ('giannis@mail.com', 'Γιάννης', 'Βασιλείου');

-- 5. Εισαγωγή Συνταγών (10 εγγραφές)
INSERT INTO RECIPE (RECIPE_ID, RNAME, INSTRUCTION, CATEGORY_ID, COUNTRY_ID) VALUES (1, 'Παστίτσιο', 'Βράζουμε τα μακαρόνια, φτιάχνουμε τον κιμά...', 4, 1);
INSERT INTO RECIPE (RECIPE_ID, RNAME, INSTRUCTION, CATEGORY_ID, COUNTRY_ID) VALUES (2, 'Καρμπονάρα', 'Ανακατεύουμε αυγά με παρμεζάνα και μπέικον...', 2, 2);
INSERT INTO RECIPE (RECIPE_ID, RNAME, INSTRUCTION, CATEGORY_ID, COUNTRY_ID) VALUES (3, 'Tacos', 'Γεμίζουμε τις τορτίγιες με κιμά και αβοκάντο...', 4, 4);
INSERT INTO RECIPE (RECIPE_ID, RNAME, INSTRUCTION, CATEGORY_ID, COUNTRY_ID) VALUES (4, 'Sushi', 'Τυλίγουμε το ρύζι με φύκια και ψάρι...', 1, 5);
INSERT INTO RECIPE (RECIPE_ID, RNAME, INSTRUCTION, CATEGORY_ID, COUNTRY_ID) VALUES (5, 'Mousse Σοκολάτας', 'Λιώνουμε τη σοκολάτα και προσθέτουμε μαρέγκα...', 3, 3);
INSERT INTO RECIPE (RECIPE_ID, RNAME, INSTRUCTION, CATEGORY_ID, COUNTRY_ID) VALUES (6, 'Χωριάτικη Σαλάτα', 'Κόβουμε ντομάτα, αγγούρι και βάζουμε φέτα...', 5, 1);
INSERT INTO RECIPE (RECIPE_ID, RNAME, INSTRUCTION, CATEGORY_ID, COUNTRY_ID) VALUES (7, 'Risotto Μανιταριών', 'Σοτάρουμε το ρύζι με τα μανιτάρια...', 2, 2);
INSERT INTO RECIPE (RECIPE_ID, RNAME, INSTRUCTION, CATEGORY_ID, COUNTRY_ID) VALUES (8, 'Γαρίδες Σαγανάκι', 'Ψήνουμε τις γαρίδες με ντομάτα και φέτα...', 1, 1);
INSERT INTO RECIPE (RECIPE_ID, RNAME, INSTRUCTION, CATEGORY_ID, COUNTRY_ID) VALUES (9, 'Κοτόπουλο Stir Fry', 'Τηγανίζουμε το κοτόπουλο με λαχανικά...', 4, 5);
INSERT INTO RECIPE (RECIPE_ID, RNAME, INSTRUCTION, CATEGORY_ID, COUNTRY_ID) VALUES (10, 'Ratatouille', 'Ψήνουμε λαχανικά στο φούρνο...', 5, 3);

-- 6. Εισαγωγή Υλικών ανά Συνταγή (RECIPE_INGREDIENTS)
-- Σύνδεση υλικών με τις συνταγές
INSERT INTO RECIPE_INGREDIENTS (RECIPE_ID, INGREDIENT_ID, MEASUREMENTS) VALUES (1, 10, '500γρ');
INSERT INTO RECIPE_INGREDIENTS (RECIPE_ID, INGREDIENT_ID, MEASUREMENTS) VALUES (1, 38, '500γρ');
INSERT INTO RECIPE_INGREDIENTS (RECIPE_ID, INGREDIENT_ID, MEASUREMENTS) VALUES (1, 39, '1 λίτρο');
INSERT INTO RECIPE_INGREDIENTS (RECIPE_ID, INGREDIENT_ID, MEASUREMENTS) VALUES (2, 10, '400γρ');
INSERT INTO RECIPE_INGREDIENTS (RECIPE_ID, INGREDIENT_ID, MEASUREMENTS) VALUES (2, 17, '3 ολόκληρα');
INSERT INTO RECIPE_INGREDIENTS (RECIPE_ID, INGREDIENT_ID, MEASUREMENTS) VALUES (3, 31, '6 κομμάτια');
INSERT INTO RECIPE_INGREDIENTS (RECIPE_ID, INGREDIENT_ID, MEASUREMENTS) VALUES (3, 32, '1 τεμάχιο');
INSERT INTO RECIPE_INGREDIENTS (RECIPE_ID, INGREDIENT_ID, MEASUREMENTS) VALUES (5, 20, '200γρ');
INSERT INTO RECIPE_INGREDIENTS (RECIPE_ID, INGREDIENT_ID, MEASUREMENTS) VALUES (6, 3, '2 τεμάχια');
INSERT INTO RECIPE_INGREDIENTS (RECIPE_ID, INGREDIENT_ID, MEASUREMENTS) VALUES (6, 13, '150γρ');
INSERT INTO RECIPE_INGREDIENTS (RECIPE_ID, INGREDIENT_ID, MEASUREMENTS) VALUES (8, 27, '500γρ');
INSERT INTO RECIPE_INGREDIENTS (RECIPE_ID, INGREDIENT_ID, MEASUREMENTS) VALUES (10, 36, '2 τεμάχια');

-- 7. Εισαγωγή Αγαπημένων (USER_FAVORITES)
-- Σύνδεση χρηστών με αγαπημένες συνταγές
INSERT INTO USER_FAVORITES (EMAIL, RECIPE_ID) VALUES ('nikos@mail.com', 1);
INSERT INTO USER_FAVORITES (EMAIL, RECIPE_ID) VALUES ('nikos@mail.com', 8);
INSERT INTO USER_FAVORITES (EMAIL, RECIPE_ID) VALUES ('maria@mail.com', 2);
INSERT INTO USER_FAVORITES (EMAIL, RECIPE_ID) VALUES ('maria@mail.com', 5);
INSERT INTO USER_FAVORITES (EMAIL, RECIPE_ID) VALUES ('eleni@mail.com', 6);
INSERT INTO USER_FAVORITES (EMAIL, RECIPE_ID) VALUES ('kostas@mail.com', 3);
INSERT INTO USER_FAVORITES (EMAIL, RECIPE_ID) VALUES ('giannis@mail.com', 4);

-- 8. Εισαγωγή Τροποποιήσεων (USERS_MODIFY)
-- Καταγραφή προτάσεων χρηστών
INSERT INTO USERS_MODIFY (EMAIL, RECIPE_ID, INGREDIENT_ID, MODIFICATION) VALUES ('nikos@mail.com', 1, 38, 'Προσθήκη λίγης κανέλας στον κιμά');
INSERT INTO USERS_MODIFY (EMAIL, RECIPE_ID, INGREDIENT_ID, MODIFICATION) VALUES ('maria@mail.com', 2, 17, 'Μόνο οι κρόκοι των αυγών για πιο κρεμώδη υφή');
INSERT INTO USERS_MODIFY (EMAIL, RECIPE_ID, INGREDIENT_ID, MODIFICATION) VALUES ('eleni@mail.com', 6, 13, 'Χρήση χαμηλών λιπαρών φέτας');
